apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  labels:
    app: solar-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: solar-system
  type: NodePort